### PR TITLE
Docker and Doxygen

### PR DESCRIPTION
**Pull request by avcuenes**

### CODE REVIEW

**Comment by avcuenes** [comment]
I add docker file to use this system at container and also add doxygen because your comment line compatible with doxygen rules

**Comment by avcuenes** [comment]
@angusleigh can you check?

**Comment by angusleigh** [comment]
Looks good! Are you able to run Rviz from the docker when you run it locally on your machine? I couldn't get it going on my machine after a quick try. I'm wondering if it's possible to fix the docker run command to do so, or if maybe we should just put a little warning that Rviz isn't supported as-is, and the user needs to figure it out for their specific configuration.

**Comment by avcuenes** [comment]
Thanks, I think rviz can be problem sometime about setting about your machine. Can you check last commits.

**Comment by angusleigh** [comment]
LGTM! Rviz works for me now with the `xhost +` addition. Thanks for the PR.

**Pull request merged**
