### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by avcuenes**

### CODE REVIEW

**Comment by avcuenes** [comment]
@angusleigh

**Comment by avcuenes** [comment]
Can anybody look this merge request?

**Comment by avcuenes** [comment]
@ewerlopes @MatthijsBurgh

**Comment by angusleigh** [comment]
Sorry, @avcuenes this is a nice PR but my review would be slow because I didn't set up many automatic tests. If you're still interested, I would like to take a look and merge it in the next couple weeks.

**Comment by avcuenes** [comment]
No problem, I gonna merge request in the next days

**Pull request closed without merging**
